// Wortschatz passend zu «Young World 3» (5. Klasse) und «Young World 4» (6. Klasse)
// Neue Wörter hinzufügen: einfach eine Zeile nach gleichem Muster ergänzen.
// Wichtig: Jedes englische und jedes deutsche Wort darf nur EINMAL vorkommen.
const WOERTER = [
  // ===== Young World 3 =====
  // Unit 1: Schools Around the World
  { de: "Schulfach", en: "subject", buch: 3, unit: 1 },
  { de: "Stundenplan", en: "timetable", buch: 3, unit: 1 },
  { de: "Schuluniform", en: "uniform", buch: 3, unit: 1 },
  { de: "Pause", en: "break", buch: 3, unit: 1 },
  { de: "lernen", en: "learn", buch: 3, unit: 1 },
  { de: "Klassenzimmer", en: "classroom", buch: 3, unit: 1 },
  { de: "Lehrerin, Lehrer", en: "teacher", buch: 3, unit: 1 },
  { de: "Schülerin, Schüler", en: "pupil", buch: 3, unit: 1 },
  { de: "Lektion", en: "lesson", buch: 3, unit: 1 },
  { de: "Pult", en: "desk", buch: 3, unit: 1 },
  { de: "Wandtafel", en: "blackboard", buch: 3, unit: 1 },
  { de: "Bleistift", en: "pencil", buch: 3, unit: 1 },
  { de: "Kugelschreiber", en: "pen", buch: 3, unit: 1 },
  { de: "Radiergummi", en: "rubber", buch: 3, unit: 1 },
  { de: "Lineal", en: "ruler", buch: 3, unit: 1 },
  { de: "Schere", en: "scissors", buch: 3, unit: 1 },
  { de: "Leim", en: "glue", buch: 3, unit: 1 },
  { de: "Schulsack", en: "school bag", buch: 3, unit: 1 },
  { de: "Bibliothek", en: "library", buch: 3, unit: 1 },
  { de: "Turnhalle", en: "gym", buch: 3, unit: 1 },
  { de: "Pausenplatz", en: "playground", buch: 3, unit: 1 },
  { de: "lesen", en: "read", buch: 3, unit: 1 },
  { de: "schreiben", en: "write", buch: 3, unit: 1 },
  { de: "zählen", en: "count", buch: 3, unit: 1 },
  { de: "zeichnen", en: "draw", buch: 3, unit: 1 },
  { de: "zuhören", en: "listen", buch: 3, unit: 1 },
  { de: "sprechen", en: "speak", buch: 3, unit: 1 },
  { de: "fragen", en: "ask", buch: 3, unit: 1 },
  { de: "antworten", en: "answer", buch: 3, unit: 1 },
  { de: "Prüfung", en: "exam", buch: 3, unit: 1 },

  // Unit 2: Friendships
  { de: "Freund, Freundin", en: "friend", buch: 3, unit: 2 },
  { de: "lustig", en: "funny", buch: 3, unit: 2 },
  { de: "schüchtern", en: "shy", buch: 3, unit: 2 },
  { de: "nett", en: "kind", buch: 3, unit: 2 },
  { de: "zusammen", en: "together", buch: 3, unit: 2 },
  { de: "lachen", en: "laugh", buch: 3, unit: 2 },
  { de: "Geheimnis", en: "secret", buch: 3, unit: 2 },
  { de: "lächeln", en: "smile", buch: 3, unit: 2 },
  { de: "weinen", en: "cry", buch: 3, unit: 2 },
  { de: "glücklich", en: "happy", buch: 3, unit: 2 },
  { de: "traurig", en: "sad", buch: 3, unit: 2 },
  { de: "wütend", en: "angry", buch: 3, unit: 2 },
  { de: "vertrauen", en: "trust", buch: 3, unit: 2 },
  { de: "teilen", en: "share", buch: 3, unit: 2 },
  { de: "streiten", en: "argue", buch: 3, unit: 2 },
  { de: "stolz", en: "proud", buch: 3, unit: 2 },
  { de: "ehrlich", en: "honest", buch: 3, unit: 2 },
  { de: "einsam", en: "lonely", buch: 3, unit: 2 },
  { de: "treffen", en: "meet", buch: 3, unit: 2 },
  { de: "reden", en: "talk", buch: 3, unit: 2 },
  { de: "Brief", en: "letter", buch: 3, unit: 2 },
  { de: "einladen", en: "invite", buch: 3, unit: 2 },
  { de: "besuchen", en: "visit", buch: 3, unit: 2 },
  { de: "umarmen", en: "hug", buch: 3, unit: 2 },
  { de: "Witz", en: "joke", buch: 3, unit: 2 },
  { de: "ruhig", en: "quiet", buch: 3, unit: 2 },
  { de: "höflich", en: "polite", buch: 3, unit: 2 },
  { de: "hilfsbereit", en: "helpful", buch: 3, unit: 2 },
  { de: "gleich", en: "same", buch: 3, unit: 2 },
  { de: "verschieden", en: "different", buch: 3, unit: 2 },

  // Unit 3: Help
  { de: "helfen", en: "help", buch: 3, unit: 3 },
  { de: "Ärztin, Arzt", en: "doctor", buch: 3, unit: 3 },
  { de: "Feuer", en: "fire", buch: 3, unit: 3 },
  { de: "Unfall", en: "accident", buch: 3, unit: 3 },
  { de: "vorsichtig", en: "careful", buch: 3, unit: 3 },
  { de: "mutig", en: "brave", buch: 3, unit: 3 },
  { de: "Spital", en: "hospital", buch: 3, unit: 3 },
  { de: "Polizei", en: "police", buch: 3, unit: 3 },
  { de: "Feuerwehrfrau, Feuerwehrmann", en: "firefighter", buch: 3, unit: 3 },
  { de: "Krankenwagen", en: "ambulance", buch: 3, unit: 3 },
  { de: "Pflegefachfrau, Pflegefachmann", en: "nurse", buch: 3, unit: 3 },
  { de: "Notfall", en: "emergency", buch: 3, unit: 3 },
  { de: "verletzt", en: "hurt", buch: 3, unit: 3 },
  { de: "Schmerz", en: "pain", buch: 3, unit: 3 },
  { de: "Blut", en: "blood", buch: 3, unit: 3 },
  { de: "gebrochen", en: "broken", buch: 3, unit: 3 },
  { de: "Verband", en: "bandage", buch: 3, unit: 3 },
  { de: "Medikament", en: "medicine", buch: 3, unit: 3 },
  { de: "krank", en: "ill", buch: 3, unit: 3 },
  { de: "gesund", en: "healthy", buch: 3, unit: 3 },
  { de: "sicher", en: "safe", buch: 3, unit: 3 },
  { de: "Gefahr", en: "danger", buch: 3, unit: 3 },
  { de: "anrufen", en: "call", buch: 3, unit: 3 },
  { de: "rufen, schreien", en: "shout", buch: 3, unit: 3 },
  { de: "retten", en: "rescue", buch: 3, unit: 3 },
  { de: "Leiter", en: "ladder", buch: 3, unit: 3 },
  { de: "Rauch", en: "smoke", buch: 3, unit: 3 },
  { de: "brennen", en: "burn", buch: 3, unit: 3 },
  { de: "Erste Hilfe", en: "first aid", buch: 3, unit: 3 },
  { de: "fallen", en: "fall", buch: 3, unit: 3 },

  // Unit 4: Festivals
  { de: "Geburtstag", en: "birthday", buch: 3, unit: 4 },
  { de: "Geschenk", en: "present", buch: 3, unit: 4 },
  { de: "Feuerwerk", en: "fireworks", buch: 3, unit: 4 },
  { de: "feiern", en: "celebrate", buch: 3, unit: 4 },
  { de: "Gast", en: "guest", buch: 3, unit: 4 },
  { de: "Kuchen", en: "cake", buch: 3, unit: 4 },
  { de: "Party", en: "party", buch: 3, unit: 4 },
  { de: "Einladung", en: "invitation", buch: 3, unit: 4 },
  { de: "Ballon", en: "balloon", buch: 3, unit: 4 },
  { de: "Glückwunschkarte", en: "card", buch: 3, unit: 4 },
  { de: "Wunsch", en: "wish", buch: 3, unit: 4 },
  { de: "Überraschung", en: "surprise", buch: 3, unit: 4 },
  { de: "Weihnachten", en: "Christmas", buch: 3, unit: 4 },
  { de: "Ostern", en: "Easter", buch: 3, unit: 4 },
  { de: "Neujahr", en: "New Year", buch: 3, unit: 4 },
  { de: "Fasnacht", en: "carnival", buch: 3, unit: 4 },
  { de: "Kostüm", en: "costume", buch: 3, unit: 4 },
  { de: "Maske", en: "mask", buch: 3, unit: 4 },
  { de: "tanzen", en: "dance", buch: 3, unit: 4 },
  { de: "singen", en: "sing", buch: 3, unit: 4 },
  { de: "Musik", en: "music", buch: 3, unit: 4 },
  { de: "Süssigkeiten", en: "sweets", buch: 3, unit: 4 },
  { de: "schmücken", en: "decorate", buch: 3, unit: 4 },
  { de: "Laterne", en: "lantern", buch: 3, unit: 4 },
  { de: "Umzug", en: "parade", buch: 3, unit: 4 },
  { de: "Tradition", en: "tradition", buch: 3, unit: 4 },
  { de: "Fest", en: "festival", buch: 3, unit: 4 },
  { de: "Hochzeit", en: "wedding", buch: 3, unit: 4 },
  { de: "Feiertag", en: "holiday", buch: 3, unit: 4 },
  { de: "besonders", en: "special", buch: 3, unit: 4 },

  // Unit 5: Sports & Games
  { de: "gewinnen", en: "win", buch: 3, unit: 5 },
  { de: "verlieren", en: "lose", buch: 3, unit: 5 },
  { de: "Mannschaft", en: "team", buch: 3, unit: 5 },
  { de: "werfen", en: "throw", buch: 3, unit: 5 },
  { de: "fangen", en: "catch", buch: 3, unit: 5 },
  { de: "springen", en: "jump", buch: 3, unit: 5 },
  { de: "schwimmen", en: "swim", buch: 3, unit: 5 },
  { de: "rennen", en: "run", buch: 3, unit: 5 },
  { de: "Wettrennen", en: "race", buch: 3, unit: 5 },
  { de: "Ball", en: "ball", buch: 3, unit: 5 },
  { de: "Tor", en: "goal", buch: 3, unit: 5 },
  { de: "Spielerin, Spieler", en: "player", buch: 3, unit: 5 },
  { de: "schiessen (Ball)", en: "kick", buch: 3, unit: 5 },
  { de: "klettern", en: "climb", buch: 3, unit: 5 },
  { de: "Velo fahren", en: "ride a bike", buch: 3, unit: 5 },
  { de: "Schlittschuh laufen", en: "skate", buch: 3, unit: 5 },
  { de: "Ski fahren", en: "ski", buch: 3, unit: 5 },
  { de: "Schlitten", en: "sledge", buch: 3, unit: 5 },
  { de: "trainieren", en: "train", buch: 3, unit: 5 },
  { de: "üben", en: "practise", buch: 3, unit: 5 },
  { de: "stark", en: "strong", buch: 3, unit: 5 },
  { de: "schwach", en: "weak", buch: 3, unit: 5 },
  { de: "langsam", en: "slow", buch: 3, unit: 5 },
  { de: "Siegerin, Sieger", en: "winner", buch: 3, unit: 5 },
  { de: "Preis", en: "prize", buch: 3, unit: 5 },
  { de: "Spiel", en: "game", buch: 3, unit: 5 },
  { de: "Würfel", en: "dice", buch: 3, unit: 5 },
  { de: "Brettspiel", en: "board game", buch: 3, unit: 5 },
  { de: "Regeln", en: "rules", buch: 3, unit: 5 },
  { de: "fair", en: "fair", buch: 3, unit: 5 },

  // ===== Young World 4 =====
  // Unit 1: The Way We Live
  { de: "aufstehen", en: "get up", buch: 4, unit: 1 },
  { de: "Frühstück", en: "breakfast", buch: 4, unit: 1 },
  { de: "Hausaufgaben", en: "homework", buch: 4, unit: 1 },
  { de: "Freizeit", en: "free time", buch: 4, unit: 1 },
  { de: "immer", en: "always", buch: 4, unit: 1 },
  { de: "nie", en: "never", buch: 4, unit: 1 },
  { de: "Dorf", en: "village", buch: 4, unit: 1 },
  { de: "Stadt", en: "town", buch: 4, unit: 1 },
  { de: "aufwachen", en: "wake up", buch: 4, unit: 1 },
  { de: "Zähne putzen", en: "brush my teeth", buch: 4, unit: 1 },
  { de: "sich anziehen", en: "get dressed", buch: 4, unit: 1 },
  { de: "Mittagessen", en: "lunch", buch: 4, unit: 1 },
  { de: "Abendessen", en: "dinner", buch: 4, unit: 1 },
  { de: "ins Bett gehen", en: "go to bed", buch: 4, unit: 1 },
  { de: "früh", en: "early", buch: 4, unit: 1 },
  { de: "spät", en: "late", buch: 4, unit: 1 },
  { de: "oft", en: "often", buch: 4, unit: 1 },
  { de: "manchmal", en: "sometimes", buch: 4, unit: 1 },
  { de: "jeden Tag", en: "every day", buch: 4, unit: 1 },
  { de: "Morgen", en: "morning", buch: 4, unit: 1 },
  { de: "Abend", en: "evening", buch: 4, unit: 1 },
  { de: "Nacht", en: "night", buch: 4, unit: 1 },
  { de: "Haus", en: "house", buch: 4, unit: 1 },
  { de: "Wohnung", en: "flat", buch: 4, unit: 1 },
  { de: "Garten", en: "garden", buch: 4, unit: 1 },
  { de: "Küche", en: "kitchen", buch: 4, unit: 1 },
  { de: "Badezimmer", en: "bathroom", buch: 4, unit: 1 },
  { de: "Schlafzimmer", en: "bedroom", buch: 4, unit: 1 },
  { de: "Wohnzimmer", en: "living room", buch: 4, unit: 1 },
  { de: "aufräumen", en: "tidy up", buch: 4, unit: 1 },

  // Unit 2: Fascinating Animal Facts
  { de: "Pferd", en: "horse", buch: 4, unit: 2 },
  { de: "gefährlich", en: "dangerous", buch: 4, unit: 2 },
  { de: "Flügel", en: "wings", buch: 4, unit: 2 },
  { de: "Schwanz", en: "tail", buch: 4, unit: 2 },
  { de: "Fell", en: "fur", buch: 4, unit: 2 },
  { de: "jagen", en: "hunt", buch: 4, unit: 2 },
  { de: "schnell", en: "fast", buch: 4, unit: 2 },
  { de: "Eier legen", en: "lay eggs", buch: 4, unit: 2 },
  { de: "Vogel", en: "bird", buch: 4, unit: 2 },
  { de: "Fisch", en: "fish", buch: 4, unit: 2 },
  { de: "Schlange", en: "snake", buch: 4, unit: 2 },
  { de: "Spinne", en: "spider", buch: 4, unit: 2 },
  { de: "Bär", en: "bear", buch: 4, unit: 2 },
  { de: "Wolf", en: "wolf", buch: 4, unit: 2 },
  { de: "Fuchs", en: "fox", buch: 4, unit: 2 },
  { de: "Eule", en: "owl", buch: 4, unit: 2 },
  { de: "Fledermaus", en: "bat", buch: 4, unit: 2 },
  { de: "Wal", en: "whale", buch: 4, unit: 2 },
  { de: "Hai", en: "shark", buch: 4, unit: 2 },
  { de: "Delfin", en: "dolphin", buch: 4, unit: 2 },
  { de: "Insekt", en: "insect", buch: 4, unit: 2 },
  { de: "Federn", en: "feathers", buch: 4, unit: 2 },
  { de: "Haut", en: "skin", buch: 4, unit: 2 },
  { de: "Zähne", en: "teeth", buch: 4, unit: 2 },
  { de: "Krallen", en: "claws", buch: 4, unit: 2 },
  { de: "Nest", en: "nest", buch: 4, unit: 2 },
  { de: "Beute", en: "prey", buch: 4, unit: 2 },
  { de: "Feind", en: "enemy", buch: 4, unit: 2 },
  { de: "giftig", en: "poisonous", buch: 4, unit: 2 },
  { de: "wild", en: "wild", buch: 4, unit: 2 },

  // Unit 3: Yesterday & Today
  { de: "gestern", en: "yesterday", buch: 4, unit: 3 },
  { de: "altmodisch", en: "old-fashioned", buch: 4, unit: 3 },
  { de: "Grosseltern", en: "grandparents", buch: 4, unit: 3 },
  { de: "Kerze", en: "candle", buch: 4, unit: 3 },
  { de: "Geschichte", en: "history", buch: 4, unit: 3 },
  { de: "erfunden", en: "invented", buch: 4, unit: 3 },
  { de: "Waschmaschine", en: "washing machine", buch: 4, unit: 3 },
  { de: "heute", en: "today", buch: 4, unit: 3 },
  { de: "morgen", en: "tomorrow", buch: 4, unit: 3 },
  { de: "Vergangenheit", en: "past", buch: 4, unit: 3 },
  { de: "Zukunft", en: "future", buch: 4, unit: 3 },
  { de: "modern", en: "modern", buch: 4, unit: 3 },
  { de: "Museum", en: "museum", buch: 4, unit: 3 },
  { de: "Schloss", en: "castle", buch: 4, unit: 3 },
  { de: "Ritter", en: "knight", buch: 4, unit: 3 },
  { de: "König", en: "king", buch: 4, unit: 3 },
  { de: "Königin", en: "queen", buch: 4, unit: 3 },
  { de: "Diener", en: "servant", buch: 4, unit: 3 },
  { de: "Bäuerin, Bauer", en: "farmer", buch: 4, unit: 3 },
  { de: "Strom", en: "electricity", buch: 4, unit: 3 },
  { de: "Telefon", en: "telephone", buch: 4, unit: 3 },
  { de: "Radio", en: "radio", buch: 4, unit: 3 },
  { de: "Zeitung", en: "newspaper", buch: 4, unit: 3 },
  { de: "sich erinnern", en: "remember", buch: 4, unit: 3 },
  { de: "vergessen", en: "forget", buch: 4, unit: 3 },
  { de: "verändern", en: "change", buch: 4, unit: 3 },
  { de: "vor langer Zeit", en: "long ago", buch: 4, unit: 3 },
  { de: "arm", en: "poor", buch: 4, unit: 3 },
  { de: "reich", en: "rich", buch: 4, unit: 3 },
  { de: "arbeiten", en: "work", buch: 4, unit: 3 },

  // Unit 4: The Call of the Alps
  { de: "Berg", en: "mountain", buch: 4, unit: 4 },
  { de: "wandern", en: "hike", buch: 4, unit: 4 },
  { de: "Kuh", en: "cow", buch: 4, unit: 4 },
  { de: "Käse", en: "cheese", buch: 4, unit: 4 },
  { de: "Tal", en: "valley", buch: 4, unit: 4 },
  { de: "Schnee", en: "snow", buch: 4, unit: 4 },
  { de: "Gipfel", en: "peak", buch: 4, unit: 4 },
  { de: "Hütte", en: "hut", buch: 4, unit: 4 },
  { de: "Ziege", en: "goat", buch: 4, unit: 4 },
  { de: "Schaf", en: "sheep", buch: 4, unit: 4 },
  { de: "Adler", en: "eagle", buch: 4, unit: 4 },
  { de: "Murmeltier", en: "marmot", buch: 4, unit: 4 },
  { de: "Wald", en: "forest", buch: 4, unit: 4 },
  { de: "See", en: "lake", buch: 4, unit: 4 },
  { de: "Fluss", en: "river", buch: 4, unit: 4 },
  { de: "Wasserfall", en: "waterfall", buch: 4, unit: 4 },
  { de: "Felsen", en: "rock", buch: 4, unit: 4 },
  { de: "Weg", en: "path", buch: 4, unit: 4 },
  { de: "Landkarte", en: "map", buch: 4, unit: 4 },
  { de: "Rucksack", en: "backpack", buch: 4, unit: 4 },
  { de: "Wetter", en: "weather", buch: 4, unit: 4 },
  { de: "Nebel", en: "fog", buch: 4, unit: 4 },
  { de: "Sturm", en: "storm", buch: 4, unit: 4 },
  { de: "Donner", en: "thunder", buch: 4, unit: 4 },
  { de: "Blitz", en: "lightning", buch: 4, unit: 4 },
  { de: "kalt", en: "cold", buch: 4, unit: 4 },
  { de: "warm", en: "warm", buch: 4, unit: 4 },
  { de: "steil", en: "steep", buch: 4, unit: 4 },
  { de: "müde", en: "tired", buch: 4, unit: 4 },
  { de: "Aussicht", en: "view", buch: 4, unit: 4 },

  // Unit 5: The Story of Chocolate
  { de: "Schokolade", en: "chocolate", buch: 4, unit: 5 },
  { de: "süss", en: "sweet", buch: 4, unit: 5 },
  { de: "Milch", en: "milk", buch: 4, unit: 5 },
  { de: "Zucker", en: "sugar", buch: 4, unit: 5 },
  { de: "Bohne", en: "bean", buch: 4, unit: 5 },
  { de: "Fabrik", en: "factory", buch: 4, unit: 5 },
  { de: "schmecken", en: "taste", buch: 4, unit: 5 },
  { de: "fein, lecker", en: "delicious", buch: 4, unit: 5 },
  { de: "Kakao", en: "cocoa", buch: 4, unit: 5 },
  { de: "Pflanze", en: "plant", buch: 4, unit: 5 },
  { de: "ernten", en: "harvest", buch: 4, unit: 5 },
  { de: "trocknen", en: "dry", buch: 4, unit: 5 },
  { de: "rösten", en: "roast", buch: 4, unit: 5 },
  { de: "mahlen", en: "grind", buch: 4, unit: 5 },
  { de: "mischen", en: "mix", buch: 4, unit: 5 },
  { de: "schmelzen", en: "melt", buch: 4, unit: 5 },
  { de: "giessen", en: "pour", buch: 4, unit: 5 },
  { de: "einpacken", en: "wrap", buch: 4, unit: 5 },
  { de: "verkaufen", en: "sell", buch: 4, unit: 5 },
  { de: "kaufen", en: "buy", buch: 4, unit: 5 },
  { de: "Laden", en: "shop", buch: 4, unit: 5 },
  { de: "Kundin, Kunde", en: "customer", buch: 4, unit: 5 },
  { de: "Schokoladentafel", en: "bar of chocolate", buch: 4, unit: 5 },
  { de: "dunkel", en: "dark", buch: 4, unit: 5 },
  { de: "bitter", en: "bitter", buch: 4, unit: 5 },
  { de: "weich", en: "soft", buch: 4, unit: 5 },
  { de: "hart", en: "hard", buch: 4, unit: 5 },
  { de: "riechen", en: "smell", buch: 4, unit: 5 },
  { de: "probieren", en: "try", buch: 4, unit: 5 },
  { de: "hungrig", en: "hungry", buch: 4, unit: 5 },
];
